### ISSUE TITLE
wuauctl force update throws  -2147024891 error

### ISSUE THREAD

**Issue by hh** [criteo-cookbooks/wsus-client#16] opened 2015-09-11 14:51 UTC
When using default attributes with the 1.2.0 release and very minimal attributes against windows 2012:

``` ruby
node.override['wsus_client'][attribute] = 'false'
```

``` ruby
wsus_client_update 'WSUS updates' do
  action             :download
end
```

https://github.com/criteo-cookbooks/wsus-client/blob/master/recipes/configure.rb#L102

``` ruby
# Force detection in case the client-side update group changed
execute 'Force Windows update detection cycle' do
  command 'c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow'
  action :nothing
end
```

``` ================================================================================
                   Error executing action `run` on resource 'execute[Force Windows update detection cycle]'
                   ================================================================================

                   Mixlib::ShellOut::ShellCommandFailed
                   ------------------------------------
                   Expected process to exit with [0], but received '-2147024891'
                   ---- Begin output of c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow ----
                   STDOUT: 
                   STDERR: 
                   ---- End output of c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow ----
                   Ran c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow returned -2147024891

                   Resource Declaration:
                   ---------------------
                   # In C:/chef/cache/cookbooks/wsus-client/recipes/configure.rb

                   102: execute 'Force Windows update detection cycle' do
                   103:   command 'c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow'
                   104:   action :nothing
                   105: end

                   Compiled Resource:
                   ------------------
                   # Declared in C:/chef/cache/cookbooks/wsus-client/recipes/configure.rb:102:in `from_file'

                   execute("Force Windows update detection cycle") do
                     action [:nothing]
                     retries 0
                     retry_delay 2
                     default_guard_interpreter :execute
                     command "c:\\windows\\sysnative\\wuauclt.exe /ResetAuthorization /DetectNow"
                     backup 5
                     returns 0
                     declared_type :execute
                     cookbook_name "wsus-client"
                     recipe_name "configure"
                   end

                   [2015-09-11T14:37:59+00:00] ERROR: Running exception handlers
                   [2015-09-11T14:37:59+00:00] ERROR: Exception handlers complete
                   [2015-09-11T14:38:00+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
                   [2015-09-11T14:38:00+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[Force Windows update detection cycle] (wsus-client::configure line 102) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected proces
s to exit with [0], but received '-2147024891'
                   ---- Begin output of c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow ----
                   STDOUT: 
                   STDERR: 
                   ---- End output of c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow ----
                   Ran c:\windows\sysnative\wuauclt.exe /ResetAuthorization /DetectNow returned -2147024891
```

Any thoughts?

**Comment by hh** [comment] 2015-09-14 11:34
It looks like we can't run this recipe via WinRM:

I'll have to figure out a way to get chef-provisioning / knife bootstrap and the like to run chef-client via a schtask.

From https://github.com/criteo-cookbooks/wsus-client#testing

``` markdown
Testing
-------
The PowerShell script will always fail if run via the winrm vagrant provider
as the IUpdateSession::CreateUpdateDownloader is not available remotely.
```

**Comment by hh** [comment] 2015-09-14 11:49
It may be possible to explicitly authenticate instead of implicitly and load the admin environment on the target machine:

From http://forum.sysinternals.com/topic5072_page1.html

```
There is an important difference between using implicit versus explicit logon: 

* psexec \\target some_command uses implicit logon to \\target. 

I.e. the user logged in locally will be used to logon to \\target. But logging in implicitly he will loose the network resources on \\target that he would have if he had logged on explicitly. 
As -e was not specified his environment will be that of the ".default" user on \\target. Check e.g. the variable %userprofile%.

* psexec \\target -u user - p passw some_command uses explicit logon to \\target. 

psexec is told to explicitly identify as user "user" on \\target (even if he is the same user "user" logged in locally). So network resources assigned to user "user" on \\target may be available. 
As -e was not specified his environment will be that of the ".default" user on \\target. Check e.g. the variable %userprofile%.

* psexec \\target -u user -p passw -e some_command uses explicit logon to \\target and loads the environment of user "user". 

Same as above plus: 
As -e was specified the environment on \\target will be that of user "user", not the one of user ".default". 

NOTE: 
Starting with psexec v1.80 the default behaviour changed! The default now is to load the correct user environment. Specifying -e will keep psexec from loading the user's environment and use the .default environment instead.
```

**Comment by jmauro** [comment] 2015-09-14 11:57
Hey,

Thanks for the report, but we won't be able to look at it before at least next week.

Regards,
JM

**Comment by jboeshart** [comment] 2015-09-29 14:33
I'm seeing this as well, and logged PR #17 which changes the `execute` resource to a `powershell_script` resource which allows it to run successfully.

**Comment by hh** [comment] 2015-09-29 18:09
Thanks @jboeshart I'll take a look soon and verify.

**Comment by hh** [comment] 2015-09-30 09:48
@jboeshart I get a bit further but now have a different error via winrm regarding the OLE downloading at https://github.com/jboeshart/wsus-client/blob/fix_force_update_detection_cycle/providers/update.rb#L41

```
knife winrm --winrm-password 'FOOBARBAZ' -m 10.113.70.186 chef-client
```

``````
[2015-09-30T09:34:41+00:00] INFO: Processing powershell_script[Force Windows update detection cycle] action run (wsus-client::configure line 102)
[2015-09-30T09:34:41+00:00] INFO: powershell_script[Force Windows update detection cycle] ran successfully
[2015-09-30T09:34:41+00:00] INFO: Processing powershell_script[Force ```
Windows update detection cycle] action nothing (wsus-client::configure line 102)
[2015-09-30T09:34:41+00:00] INFO: Processing wsus_client_update[WSUS updates] action download (wsus-client::update line 31)
[2015-09-30T09:34:46+00:00] INFO: Windows Auto Update: 41 update(s) to download.

================================================================================
Error executing action `download` on resource 'wsus_client_update[WSUS updates]'
================================================================================

WIN32OLERuntimeError
--------------------
(in OLE method `CreateUpdateDownloader': )
    OLE error code:80070005 in <Unknown>
      <No Description>
    HRESULT error code:0x80020009
      Exception occurred.

Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/wsus-client/recipes/update.rb

 31: wsus_client_update 'WSUS updates' do
 32:   action             actions_to_perform
 33: end

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/wsus-client/recipes/update.rb:31:in `from_file'

wsus_client_update("WSUS updates") do
  action [:download, :install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :wsus_client_update
  cookbook_name "wsus-client"
  recipe_name "update"
end

[2015-09-30T09:34:46+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-09-30T09:34:46+00:00] ERROR: Running exception handlers
[2015-09-30T09:34:46+00:00] ERROR: Exception handlers complete
[2015-09-30T09:34:46+00:00] INFO: Sending resource update report (run-id: a2be1e12-eebb-4e29-aa0a-89206a85eba0)
[2015-09-30T09:34:47+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2015-09-30T09:34:47+00:00] FATAL: WIN32OLERuntimeError: wsus_client_update[WSUS updates] (wsus-client::update line 31) had an error: WIN32OLERuntimeError: (in OLE method `CreateUpdateDownloader': )
    OLE error code:80070005 in <Unknown>
      <No Description>
    HRESULT error code:0x80020009
      Exception occurred.
ERROR: Failed to execute command on 10.113.70.186 return code 1
``````

```
$ ./bin/winrm mip-2012-test-4 'type c:\chef\cache\chef-stacktrace.out'
Retrieving instance id and ip address and password for mip-2012-test-4 type c:\chef\cache\chef-stacktrace.out
knife winrm --winrm-password PASSWORD -m type c:\chef\cache\chef-stacktrace.out
Generated at 2015-09-30 09:40:55 +0000
WIN32OLERuntimeError: wsus_client_update
[WSUS updates] (wsus-client::update line 31) had an error: WIN32OLERuntimeError: (in OLE method `CreateUpdateDownloader': )
    OLE error code:80070005 in <Unknown>
      <No Description>
    HRESULT error code:0x80020009
      Exception occurred.
C:/chef/cache/cookbooks/wsus-client/providers/update.rb:41:in `method_missing'
C:/chef/cache/cookbooks/wsus-client/providers/update.rb:41:in `block (2 levels) in class_from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
C:/chef/cache/cookbooks/wsus-client/providers/update.rb:36:in `block in class_from_file'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:46:in `block in action'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:67:in `load'
C:/opscode/chef/bin/chef-client:67:in `<main>'
```

**Comment by hh** [comment] 2015-09-30 10:03
If there are no updates, there are no errors here:

```
[2015-09-30T10:01:54+00:00] INFO: Processing wsus_client_update[WSUS updates] action download (wsus-client::update line 31)
[2015-09-30T10:03:04+00:00] INFO: Processing wsus_client_update[WSUS updates] action install (wsus-client::update line 31)
```

**Comment by jboeshart** [comment] 2015-09-30 13:30
That appears to be a different issue since it's in the update LWRP rather than the config recipe, and is likely the issue that is mentioned in the Testing section of the readme that you mentioned previously. Does it work if you log on locally and run chef-client? What is your end goal with using the update LWRP? Is it to fully manage the Windows updates through Chef or is it to just kick off an initial update, then relying on the server configuration for subsequent updates?

**Comment by hh** [comment] 2015-09-30 14:20
Yeah, it works via schtask and rdp desktop.
The goal is to bootstrap windows nodes (from AMI's provided by amazon) and run recipes and save new images hands off / all automated with chef.
Those initial images do not have updates applied.
I think there may also need to be some logic to detect when a reboot is required to for updates (I'm also installing some IIS windows_features). It's available in the desktop interface as notices to reboot to finish updates etc. But not via wsus-client cookbook.

**Comment by jboeshart** [comment] 2015-09-30 14:41
Yeah, sounds like the issue mentioned in the readme. If it helps, I've got a script [1] that you could use to do updates instead of relying on the Windows Update service. You finagle something with a scheduled task or something, since I don't know that it would work through WinRM either as it uses the same objects that the update recipe does. It will handle reboots if needed as well. I'm doing something similar for nodes in AWS, but want to not have to mess with GPO to configure/schedule/run Windows Update, and this has seemed to work so far (though I'm still a bit early in the process). 

[1] https://github.com/jboeshart/code/blob/master/powershell/Apply-WindowsUpdates.ps1

**Comment by brugidou** [comment] 2015-10-01 06:28
Indeed it is not possible to run this cookbook in a winrm session as specified in the readme. A workaround is to create a scheduled task from winrm, run this task (generally as SYSTEM user) and delete the task afterwards.

**Comment by Annih** [comment] 2015-10-01 07:41
Hello Guys :)

Sorry for the delay, thanks for your patience and all your investigations on this topic.
I think you currently have 2 issues:
1. strange exit code on the `execute wuauclt` (which should work with winrm)
2. update LWRP failing when run remotely (which is the behavior described in the README)

For `1.` I would need more information on the procedure to reproduce:
- which chef version do you run
- what particularity has your Windows 2012R2 image
- did you apply any other configuration/gpo ?

For `2.` I think I won't be able to provide you a better solution than a Schedule task.

Regards.

**Comment by jboeshart** [comment] 2015-10-01 19:01
I'm running the latest Chef Omnibus installer (12.4.3) testing locally using Vagrant and Test Kitchen. I'm running Windows 2012r2 with the base install and no additional configuration or policies. 

`c:\windows\sysnative` is only intended for use within 32-bit applications [1], so I'm wondering if that's causing some of the issues, though if I change it to `c:\windows\system32` it for some reason can't even find the wuauclt.exe executable. If I use the powershell_script resource it works, even without requiring the specification of the path to wuauclt.exe. I ran a procmon trace to see if that showed anything. It shows the wuauctl.exe process starting, then it just exits with that access denied error code. There's a number of posts on the Googles with the same error when trying to kick that same command off remotely with tools like psexec that are fixed by specifying credentials. This leads me to think that it's something with the way Ruby/ShellOut is creating the shell, but I've yet to find anything definitive other than it works with `powershell_script` and doesn't with `execute`. 

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/aa384187(v=vs.85).aspx

**Comment by Annih** [comment] 2015-12-02 10:44
Hello @hh 

Again thanks for you contribution, this issue is clearly related to winrm limitation and not wsus-client cookbook, so I'll not fix it sorry.

However I'm trying to push chef windows contributors to fix this issue using schedule task (as you did in your issue at chef-provisioning) in all related technologies:
- [test-kitchen#876](https://github.com/test-kitchen/test-kitchen/issues/876)
- [knife-windows#318](https://github.com/chef/knife-windows/issues/318)
- [chef-provisioning#443](https://github.com/chef/chef-provisioning/issues/443) - it's yours!!

Regards,

Annih

**Closed as completed by Annih** 2015-12-02 10:44 UTC
Labels: wontfix

**Comment by hh** [comment] 2015-12-02 13:54
This might be of related interest: https://github.com/WinRb/winrm-elevated

**Comment by Annih** [comment] 2015-12-02 14:48
Yep, it could be very cool if test-kitchen, knife-windows and chef-provisioning were using this gem :)
